<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" ignored="0" total="6" passed="0">
  <reporter-output>
    <line>
      <![CDATA[STEP1]]>
    </line>
    <line>
      <![CDATA[STEP2]]>
    </line>
    <line>
      <![CDATA[STEP3]]>
    </line>
    <line>
      <![CDATA[STEP4]]>
    </line>
    <line>
      <![CDATA[STEP5]]>
    </line>
    <line>
      <![CDATA[STEP6]]>
    </line>
    <line>
      <![CDATA[STEP7]]>
    </line>
    <line>
      <![CDATA[STEP8]]>
    </line>
    <line>
      <![CDATA[STEP9]]>
    </line>
    <line>
      <![CDATA[STEP10]]>
    </line>
    <line>
      <![CDATA[STEP11]]>
    </line>
    <line>
      <![CDATA[STEP12]]>
    </line>
    <line>
      <![CDATA[STEP13]]>
    </line>
    <line>
      <![CDATA[STEP14]]>
    </line>
    <line>
      <![CDATA[STEP15]]>
    </line>
    <line>
      <![CDATA[STEP16]]>
    </line>
    <line>
      <![CDATA[STEP17]]>
    </line>
    <line>
      <![CDATA[STEP18]]>
    </line>
    <line>
      <![CDATA[STEP19]]>
    </line>
    <line>
      <![CDATA[STEP20]]>
    </line>
    <line>
      <![CDATA[STEP21]]>
    </line>
    <line>
      <![CDATA[STEP22]]>
    </line>
    <line>
      <![CDATA[STEP23]]>
    </line>
    <line>
      <![CDATA[STEP24]]>
    </line>
    <line>
      <![CDATA[STEP25]]>
    </line>
    <line>
      <![CDATA[STEP26]]>
    </line>
    <line>
      <![CDATA[STEP27]]>
    </line>
    <line>
      <![CDATA[STEP28]]>
    </line>
    <line>
      <![CDATA[STEP29]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="106868" started-at="2019-08-24T10:17:51Z" finished-at="2019-08-24T10:19:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="106868" started-at="2019-08-24T10:17:51Z" finished-at="2019-08-24T10:19:38Z">
      <class name="com.jocata.tbml.testcases.LoginPage">
        <test-method status="PASS" signature="BeforeTest()[pri:0, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="BeforeTest" is-config="true" duration-ms="541" started-at="2019-08-24T10:17:51Z" finished-at="2019-08-24T10:17:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTest -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="BeforeMethod" is-config="true" duration-ms="126" started-at="2019-08-24T10:17:52Z" finished-at="2019-08-24T10:17:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="validuser()[pri:1, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="validuser" duration-ms="13169" started-at="2019-08-24T10:17:52Z" finished-at="2019-08-24T10:18:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.jocata.tbml.framework.TakeAction.click(TakeAction.java:181)
at com.jocata.tbml.framework.Driver.doAction(Driver.java:208)
at com.jocata.tbml.framework.Driver.runKeyValue(Driver.java:150)
at com.jocata.tbml.testcases.LoginPage.validuser(LoginPage.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[STEP1]]>
            </line>
            <line>
              <![CDATA[STEP2]]>
            </line>
            <line>
              <![CDATA[STEP3]]>
            </line>
            <line>
              <![CDATA[STEP4]]>
            </line>
            <line>
              <![CDATA[STEP5]]>
            </line>
            <line>
              <![CDATA[STEP6]]>
            </line>
            <line>
              <![CDATA[STEP7]]>
            </line>
            <line>
              <![CDATA[STEP8]]>
            </line>
          </reporter-output>
        </test-method> <!-- validuser -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="AfterMethod" is-config="true" duration-ms="26" started-at="2019-08-24T10:18:05Z" finished-at="2019-08-24T10:18:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="BeforeMethod" is-config="true" duration-ms="64" started-at="2019-08-24T10:18:05Z" finished-at="2019-08-24T10:18:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="invaliduser()[pri:2, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="invaliduser" duration-ms="37252" started-at="2019-08-24T10:18:05Z" finished-at="2019-08-24T10:18:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.jocata.tbml.framework.TakeAction.type(TakeAction.java:1414)
at com.jocata.tbml.framework.Driver.doAction(Driver.java:194)
at com.jocata.tbml.framework.Driver.runKeyValue(Driver.java:150)
at com.jocata.tbml.testcases.LoginPage.invaliduser(LoginPage.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[STEP9]]>
            </line>
            <line>
              <![CDATA[STEP10]]>
            </line>
            <line>
              <![CDATA[STEP11]]>
            </line>
            <line>
              <![CDATA[STEP12]]>
            </line>
            <line>
              <![CDATA[STEP13]]>
            </line>
          </reporter-output>
        </test-method> <!-- invaliduser -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="AfterMethod" is-config="true" duration-ms="3" started-at="2019-08-24T10:18:42Z" finished-at="2019-08-24T10:18:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="BeforeMethod" is-config="true" duration-ms="78" started-at="2019-08-24T10:18:42Z" finished-at="2019-08-24T10:18:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="invalidpwd()[pri:3, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="invalidpwd" duration-ms="13404" started-at="2019-08-24T10:18:42Z" finished-at="2019-08-24T10:18:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.jocata.tbml.framework.TakeAction.type(TakeAction.java:1414)
at com.jocata.tbml.framework.Driver.doAction(Driver.java:194)
at com.jocata.tbml.framework.Driver.runKeyValue(Driver.java:150)
at com.jocata.tbml.testcases.LoginPage.invalidpwd(LoginPage.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[STEP14]]>
            </line>
            <line>
              <![CDATA[STEP15]]>
            </line>
            <line>
              <![CDATA[STEP16]]>
            </line>
            <line>
              <![CDATA[STEP17]]>
            </line>
          </reporter-output>
        </test-method> <!-- invalidpwd -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="AfterMethod" is-config="true" duration-ms="1" started-at="2019-08-24T10:18:56Z" finished-at="2019-08-24T10:18:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="BeforeMethod" is-config="true" duration-ms="53" started-at="2019-08-24T10:18:56Z" finished-at="2019-08-24T10:18:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="invaliduserpwd()[pri:4, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="invaliduserpwd" duration-ms="14003" started-at="2019-08-24T10:18:56Z" finished-at="2019-08-24T10:19:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.jocata.tbml.framework.TakeAction.type(TakeAction.java:1414)
at com.jocata.tbml.framework.Driver.doAction(Driver.java:194)
at com.jocata.tbml.framework.Driver.runKeyValue(Driver.java:150)
at com.jocata.tbml.testcases.LoginPage.invaliduserpwd(LoginPage.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[STEP18]]>
            </line>
            <line>
              <![CDATA[STEP19]]>
            </line>
            <line>
              <![CDATA[STEP20]]>
            </line>
            <line>
              <![CDATA[STEP21]]>
            </line>
          </reporter-output>
        </test-method> <!-- invaliduserpwd -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="AfterMethod" is-config="true" duration-ms="10" started-at="2019-08-24T10:19:10Z" finished-at="2019-08-24T10:19:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="BeforeMethod" is-config="true" duration-ms="57" started-at="2019-08-24T10:19:10Z" finished-at="2019-08-24T10:19:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="withoutDetails()[pri:5, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="withoutDetails" duration-ms="13050" started-at="2019-08-24T10:19:10Z" finished-at="2019-08-24T10:19:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.jocata.tbml.framework.TakeAction.click(TakeAction.java:176)
at com.jocata.tbml.framework.Driver.doAction(Driver.java:208)
at com.jocata.tbml.framework.Driver.runKeyValue(Driver.java:150)
at com.jocata.tbml.testcases.LoginPage.withoutDetails(LoginPage.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[STEP22]]>
            </line>
            <line>
              <![CDATA[STEP23]]>
            </line>
            <line>
              <![CDATA[STEP24]]>
            </line>
            <line>
              <![CDATA[STEP25]]>
            </line>
          </reporter-output>
        </test-method> <!-- withoutDetails -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="AfterMethod" is-config="true" duration-ms="4" started-at="2019-08-24T10:19:23Z" finished-at="2019-08-24T10:19:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="BeforeMethod" is-config="true" duration-ms="59" started-at="2019-08-24T10:19:23Z" finished-at="2019-08-24T10:19:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="clickOnOkBtn()[pri:6, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="clickOnOkBtn" duration-ms="13721" started-at="2019-08-24T10:19:23Z" finished-at="2019-08-24T10:19:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.jocata.tbml.framework.TakeAction.click(TakeAction.java:176)
at com.jocata.tbml.framework.Driver.doAction(Driver.java:208)
at com.jocata.tbml.framework.Driver.runKeyValue(Driver.java:150)
at com.jocata.tbml.testcases.LoginPage.clickOnOkBtn(LoginPage.java:98)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[STEP26]]>
            </line>
            <line>
              <![CDATA[STEP27]]>
            </line>
            <line>
              <![CDATA[STEP28]]>
            </line>
            <line>
              <![CDATA[STEP29]]>
            </line>
          </reporter-output>
        </test-method> <!-- clickOnOkBtn -->
        <test-method status="PASS" signature="AfterMethod()[pri:0, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="AfterMethod" is-config="true" duration-ms="0" started-at="2019-08-24T10:19:37Z" finished-at="2019-08-24T10:19:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="AfterTest()[pri:0, instance:com.jocata.tbml.testcases.LoginPage@41330d4f]" name="AfterTest" is-config="true" duration-ms="1189" started-at="2019-08-24T10:19:37Z" finished-at="2019-08-24T10:19:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTest -->
      </class> <!-- com.jocata.tbml.testcases.LoginPage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
